version: '2'

services:
  web:
    build: .
    command: python3 manage.py migrate
    command: python3 manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
  db:
    image: datajoint/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=casa
      - MYSQL_PASSWORD=123     
      - MYSQL_ROOT_PASSWORD=123 
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8082:80
    volumes:
      - /sessions
    links:
      - db
    depends_on:
      - db
