# Generated by Django 2.2.dev20180828184008 on 2018-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='hospedado',
            field=models.BooleanField(default=False),
        ),
    ]
