# Generated by Django 2.2.dev20180915135820 on 2018-09-16 12:34

import casa_danielli.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0002_paciente_hospedado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='inclusao',
            field=models.DateTimeField(blank=True, default=casa_danielli.models.return_date_time, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='validade',
            field=models.DateField(blank=True, default=casa_danielli.models.return_date_time, null=True),
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_ap', models.CharField(blank=True, max_length=255, null=True)),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('cafe_manha', models.BooleanField(default=False)),
                ('almoco', models.BooleanField(default=False)),
                ('cafe_tarde', models.BooleanField(default=False)),
                ('banho', models.BooleanField(default=False)),
                ('janta', models.BooleanField(default=False)),
                ('hospedagem', models.CharField(blank=True, max_length=255, null=True)),
                ('inclusao', models.DateTimeField(blank=True, default=casa_danielli.models.return_date_time, null=True)),
                ('atualizacao', models.DateTimeField(blank=True, default=casa_danielli.models.return_date_time, null=True)),
                ('usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('nome', models.ManyToManyField(related_name='Acolhidos', to='casa_danielli.Paciente')),
            ],
            options={
                'managed': True,
                'db_table': 'acompanhamento',
            },
        ),
        migrations.CreateModel(
            name='Acolhidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_danielli.Acompanhamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_danielli.Paciente')),
            ],
        ),
    ]
