# Generated by Django 2.2.dev20180916132525 on 2018-09-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0004_acompanhamento_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='nome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='casa_danielli.Paciente'),
        ),
        migrations.DeleteModel(
            name='Acolhidos',
        ),
    ]
