# Generated by Django 2.2.dev20180916132525 on 2018-09-20 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0005_auto_20180920_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa_danielli.Paciente'),
        ),
    ]
