# Generated by Django 2.2.dev20180920190433 on 2018-09-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0008_auto_20180920_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='ativo',
        ),
    ]
