# Generated by Django 2.2.dev20180922200754 on 2018-09-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0009_remove_acompanhamento_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obito',
            field=models.BooleanField(default=False),
        ),
    ]
