# Generated by Django 2.2.dev20180924184437 on 2018-09-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0010_paciente_obito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='validade',
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
