# Generated by Django 2.2.dev20180924184437 on 2018-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0011_auto_20180929_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='ac_ap',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
