# Generated by Django 2.2.dev20180924184437 on 2018-09-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0012_auto_20180929_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='hospedagem',
            field=models.BooleanField(default=False),
        ),
    ]
