# Generated by Django 2.2.dev20180924184437 on 2018-09-29 12:29

import casa_danielli.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0013_auto_20180929_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento',
            name='atualizacao',
        ),
        migrations.AddField(
            model_name='acompanhamento',
            name='saida',
            field=models.DateField(blank=True, default=casa_danielli.models.return_date_time, null=True),
        ),
        migrations.AlterField(
            model_name='acompanhamento',
            name='inclusao',
            field=models.DateField(blank=True, default=casa_danielli.models.return_date_time, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='atualizacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='inclusao',
            field=models.DateField(blank=True, default=casa_danielli.models.return_date_time, null=True),
        ),
    ]
