# Generated by Django 2.2.dev20180929132502 on 2018-09-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa_danielli', '0015_auto_20180929_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acompanhamento',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
